name: Build and deploy ASP.Net Framework app to Azure Web App - CourierApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v3

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build and Publish to Folder
        run: msbuild MyCourierService\MyCourierService.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:publishUrl="${{ github.workspace }}\output"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}\output

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}\output
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_957D76E9E7734ACEBEC0FAF35DEB5BD7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D8762F8F53344BD4A29370AA05227029 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA69F07A657A41A9932E89D76B5C5002 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CourierApp'
          slot-name: 'Production'
          package: ${{ github.workspace }}\output
